### ISSUE TITLE
64 bits support

### ISSUE THREAD

**Issue by bablydas** [FokkeZB/ti-html2as#10]
Can you please provide support for 64 bits. 

Thanks.

**Comment by yuchi** [comment]
It's a fully JS module, so you shouldn't have any issue with 64bit :)

**Comment by bablydas** [comment]
Sorry! I actually meant the widget. I think I posted in the wrong place.

**Comment by FokkeZB** [comment]
Same for the widget.. it's JS

Where do you get a 64-bit error that makes you think the module/widget needs updating?

**Comment by bablydas** [comment]
I am trying to use the widget and I am getting an error -
[ERROR] :  Script Error Couldn't find module: nl.fokkezb.html2as for architecture: i386

Sorry for my ignorance but being relatively new to app development when I got that error I thought the widget needs to be updated for 64 bits.  Thanks.

**Comment by FokkeZB** [comment]
Mmm, I guess CommonJS modules are checked for architectures as well.

Thanks @bablydas, I will take this up with AppC engineering.

**Comment by FokkeZB** [comment]
@bablydas I can't reproduce this. Can you give the exact steps to reproduce?

What I did was running `grunt` to create and run the example app (3.5.0.GA) and when that worked fine, I also deployed it to device, which also worked.

**Comment by santiobando** [comment]
@bablydas have you tried adding the widget to the config.json file? It solved this error for me.

    "dependencies": {
        "existingWidgetName": "1.0",
        "newWidgetName": "1.0"
    }

**Comment by bablydas** [comment]
Thanks all. I managed to solve the issue by adding the module to my project as well.

**Comment by PietroGranati** [comment]
For me the error is still alive
