### ISSUE TITLE
Mobile web build gives an error

### ISSUE THREAD

**Issue by vinzentt** [FokkeZB/ti-html2as#14]
Hi, 

I was trying to build for mobileweb and got this error:
[ERROR] Invalid Titanium Mobile Module "nl.fokkezb.html2as": unable to find main file "index.js"

I installed the widget through gittio, any ideas?

Thanks.

**Comment by FokkeZB** [comment]
@vinzentt You've spotted a bug in Titaniumifier. As soon as it is fixed I'll do a new version.
