### ISSUE TITLE
Error message when running the project 

### ISSUE THREAD

**Issue by pakoArtal** [FokkeZB/ti-html2as#29]
Hi Fokke,

In the Project Explorer I see a red sign next to modules/commonjs/nl.fokkezb.html2as.js because there are some semicolons missing at the first block. 

When I Run or Debug my project I get the following error:
Errors in Workspace
Error exist in required project(s):
myProject
Proceed with launch?

I know this 'issue' it is not important as I can run the project without problems.
I was going to solve myself but I don't know how to 'compress'  the code again. Could you give me any advice on it?

Thanks.

**Comment by FokkeZB** [comment]
Hi @pakoArtal, thanks! Just submit a PR with the fixes in the uncompressed code and I'll run titaniumifier on it. However, it might well be that the source files are fine and that the compression titaniumifier does causes the linting errors. In that case there's not much I can do about that.

**Comment by yuchi** [comment]
If the issue is not in the source code but on the bundled code you need to skip the linting validation for the `modules` folder. If you’re using the JSLint plugin for Eclipse I’m sure there’s an option for that, an `exclude` in the config file probably.
