### ISSUE TITLE
Underline with css-style containing underline

### ISSUE THREAD

**Issue by m1ga** [FokkeZB/ti-html2as#36]
I have some HTML code where I have no `<u>` but a CSS style with `text-decoration:underline`. In my case I know its only for spans so I could use a regex to replace it with `<u>`

But perhaps it would be a good addition to add a check for something like `node.attribs && node.attribs.style.indexOf("underline")>-1` at `ATTRIBUTE_UNDERLINES_STYLE`

Democode: 
` asdf <span style='font-size:12; text-decoration: underline;'>fa1111sdf</span> adsf  sadf`

**Comment by FokkeZB** [comment]
Sorry, but I don't like the idea of supporting selective CSS. Instead, I'd suggest you do a separate regex replace to change this into a "u" before passing it to this module.
