### ISSUE TITLE
Error: "Cannot read property 'replace' of undefined"

### ISSUE THREAD

**Issue by chmiiller** [FokkeZB/ti-html2as#37]
[Android]
Do you have any idea why this is happening?
Module was working just fine on Ti SDK 5 and doesn't work on Ti SDK 6.0 with this error.
Don't know what to do =/

**Comment by FokkeZB** [comment]
Do you have a backtrace? It looks like this originates from these lines:

https://github.com/FokkeZB/ti-html2as/blob/9ab0484f2df7388944cb227f40d28a8934db64cd/index.js#L200-L203

That would mean that you pass an `undefined` to the module.

**Comment by chmiiller** [comment]
You're right, I was getting an undefined.
Going to close this issue. Thanks
