### ISSUE TITLE
\n not working in android

### ISSUE THREAD

**Issue by vivekgidmare** [FokkeZB/ti-html2as#7]
\n using for new line is not working on android same code is working on iOS

**Comment by vivekgidmare** [comment]
use <br> instead of \n in android for new line

**Comment by FokkeZB** [comment]
Glad you found a workaround but I'd rather make it cross platform identical. Reopening.

**Comment by vivekgidmare** [comment]
Ok that would be great to avoid platform specific code.

**Comment by FokkeZB** [comment]
I guess we should not alter how `html` works for Android. So then the proper thing to do would be to strip out `\n|\r` for iOS, so you need to use `<br />` there as well.

**Comment by beaurushton** [comment]
I'd like to see cross platform support for <br> tags, possibly also a way to convert <p> tags to <br> as well.
